version: '3'

services:
  www:
    image: $DOCKER_TAG
    container_name: ghyt-ci-www
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - YOUTRACK_TOKEN
      - YOUTRACK_HOST
      - GITHUB_TOKEN
      - GITHUB_SECRET
      - GITHUB_WEB_HOOK_DB
      - GH_WEBSOCKET_SECRET
      - GITHUB_APP_KEY_FILE
      - PR_BRANCH_YT_CHECK
      - DISABLE_CHECK_API
    command: >
      bash -c "perl /opt/git/github-youtrack/docker/init.sh && /opt/git/github-youtrack/github_web_hook.pl daemon -m production -l http://*:3000"
    networks:
      ghyt-ci-nw:
        ipv4_address: 192.168.1.10
    volumes:
      - ghyt_ci_vol:/tmp
  spooler:
    image: $DOCKER_TAG
    container_name: ghyt-ci-spooler
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - YOUTRACK_TOKEN
      - YOUTRACK_HOST
      - GITHUB_TOKEN
      - GITHUB_SECRET
      - GITHUB_WEB_HOOK_DB
      - GH_WEBSOCKET_SECRET
      - GITHUB_APP_KEY_FILE
      - PR_BRANCH_YT_CHECK
      - DISABLE_CHECK_API
    command: >
      bash -c "/usr/local/bin/dockerize --wait http://ghyt-ci-www:3000/ghyt-ci && /opt/git/github-youtrack/check_spooler.pl"
    networks:
      ghyt-ci-nw:
        ipv4_address: 192.168.1.11
    volumes:
      - ghyt_ci_vol:/tmp

networks:
  ghyt-ci-nw:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  ghyt_ci_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

