version: '3'

services:
  www:
    image: $DOCKER_TAG
    container_name: micro-ci-www
    expose:
      - 80
    environment:
      - YOUTRACK_TOKEN
      - YOUTRACK_HOST
      - GITHUB_TOKEN
      - GITHUB_SECRET
      - GITHUB_WEB_HOOK_DB
      - GH_WEBSOCKET_SECRET
      - GITHUB_APP_KEY_FILE
      - PR_BRANCH_YT_CHECK
      - DISABLE_CHECK_API
    command: >
      bash -c "perl /opt/git/github-youtrack/docker/init.sh && /opt/git/github-youtrack/github_web_hook.pl daemon -m production -l http://*:80"
    networks:
      micro-ci-nw:
        ipv4_address: 192.168.1.10
    volumes:
      - run_vol_mci:/run
  spooler:
    image: $DOCKER_TAG
    container_name: micro-ci-spooler
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - YOUTRACK_TOKEN
      - YOUTRACK_HOST
      - GITHUB_TOKEN
      - GITHUB_SECRET
      - GITHUB_WEB_HOOK_DB
      - GH_WEBSOCKET_SECRET
      - GITHUB_APP_KEY_FILE
      - PR_BRANCH_YT_CHECK
      - DISABLE_CHECK_API
    command: >
      bash -c "perl /opt/git/github-youtrack/docker/init.sh && /opt/git/github-youtrack/check_spooler.pl"
    networks:
      micro-ci-nw:
        ipv4_address: 192.168.1.11
    volumes:
      - run_vol_mci:/run

networks:
  micro-ci-nw:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  run_vol_mci:
    driver_opts:
      type: tmpfs
      device: tmpfs

